server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.120.147:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos
          uri: lb://nacos
          order: 1
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1
        - id: finance
          uri: lb://finance
          order: 1
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
