server:
  port: 8010

spring:
  application:
    name: security
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.120.147:8848

  redis:
    port: 6379
    database: 0
    host: 47.106.120.147